export enum TaskType {
  LAUNCH_BROWSER = "LAUNCH_BROWSER",
  PAGE_TO_HTML = "PAGE_TO_HTML",
  EXTRACT_TEXT_FROM_ELEMENT = "EXTRACT_TEXT_FROM_ELEMENT",
  FILL_INPUT = "FILL_INPUT",
  CLICK_ELEMENT = "CLICK_ELEMENT",
  WAIT_FOR_ELEMENT = "WAIT_FOR_ELEMENT",
  DELIVER_VIA_WEBHOOK = "DELIVER_VIA_WEBHOOK",
  EXTRACT_DATA_WITH_AI = "EXTRACT_DATA_WITH_AI",
  READ_PROPERTY_FROM_JSON = "READ_PROPERTY_FROM_JSON",
  ADD_PROPERTY_TO_JSON = "ADD_PROPERTY_TO_JSON",
  NAVIGATE_URL = "NAVIGATE_URL",
  SCROLL_TO_ELEMENT = "SCROLL_TO_ELEMENT",
  // ── NEW: Browser Actions ──
  INFINITE_SCROLL = "INFINITE_SCROLL", // NEW
  RANDOM_DELAY = "RANDOM_DELAY", // NEW
  SESSION_COOKIES = "SESSION_COOKIES", // NEW

  // ── NEW: Data Extraction ──
  EXTRACT_STRUCTURED_LIST = "EXTRACT_STRUCTURED_LIST", // NEW
  EXTRACT_STRUCTURED_OBJECT = "EXTRACT_STRUCTURED_OBJECT", // NEW
  EXTRACT_TABLE_DATA = "EXTRACT_TABLE_DATA", // NEW

  // ── NEW: Data Processing ──
  FILTER_ARRAY = "FILTER_ARRAY", // NEW
  CONVERT_FIELDS_TO_NUMBER = "CONVERT_FIELDS_TO_NUMBER", // NEW
  TRANSFORM_ARRAYS_TO_OBJECTS = "TRANSFORM_ARRAYS_TO_OBJECTS", // NEW

  // ── NEW: Flow Control ──
  LOOP_START_ARRAY = "LOOP_START_ARRAY", // NEW
  LOOP_START_REPEAT = "LOOP_START_REPEAT", // NEW
  LOOP_START_UNTIL_CONDITION = "LOOP_START_UNTIL_CONDITION", // NEW
  LOOP_END = "LOOP_END", // NEW
  FLOW_CONTROL_ACTION = "FLOW_CONTROL_ACTION", // NEW
  IF_CONDITION = "IF_CONDITION", // NEW
  STOP_WORKFLOW = "STOP_WORKFLOW", // NEW
  BATCH_LOOP_OVER = "BATCH_LOOP_OVER", // NEW

  // ── NEW: Data Analytics ──
  SENTIMENT_ANALYZER = "SENTIMENT_ANALYZER", // NEW
  AI_SUMMARIZER = "AI_SUMMARIZER", // NEW
  VISUALIZER = "VISUALIZER", // NEW
  GENERATE_ANALYTICAL_REPORT = "GENERATE_ANALYTICAL_REPORT", // NEW

  // ── NEW: Output Delivery ──
  EXPORT_CSV = "EXPORT_CSV", // NEW
}
export enum TaskParamType {
  STRING = "STRING",
  BROWSER_INSTANCE = "BROWSER_INSTANCE",
  SELECT = "SELECT",
  CREDENTIAL = "CREDENTIAL",
  // ── NEW params ──
  EXTRACTION_FIELDS = "EXTRACTION_FIELDS", // NEW — field selector UI
  FILTER_CONDITIONS = "FILTER_CONDITIONS", // NEW — filter builder UI
  CHART_CONFIG = "CHART_CONFIG", // NEW — chart config UI
  SESSION_PARAM = "SESSION_PARAM", // NEW — session/cookie input
}

export interface TaskParam {
  name: string;
  type: TaskParamType;
  helperText?: string;
  required?: boolean;
  hideHandle?: boolean;
  value?: string;
  defaultValue?: any;
  [key: string]: any;
}
